# Generated by Django 5.1.1 on 2024-10-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0002_alter_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
