# Generated by Django 5.1.1 on 2024-10-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0007_remove_product_created_at_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
