# Generated by Django 5.1.1 on 2024-11-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_remove_cart_updated_at_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
