# Generated by Django 5.1.1 on 2024-11-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
