# Generated by Django 5.1.1 on 2024-11-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_order'),
        ('Farmer', '0008_alter_product_name_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Farmer.product'),
        ),
    ]
