# Generated by Django 5.1.1 on 2024-11-06 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
