# Generated by Django 5.1.1 on 2024-11-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_order_order_time'),
        ('Farmer', '0008_alter_product_name_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='Farmer.product'),
        ),
    ]
