# Generated by Django 5.1.1 on 2024-11-06 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_remove_order_order_time_alter_order_contact_and_more'),
        ('Farmer', '0008_alter_product_name_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Farmer.product')),
            ],
        ),
    ]
